name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'
    - name: Set up Python
      uses: actions/setup-python@v5
    - name: Setup OTA settings file
      run: |
        cp ota.ini.example ota.ini
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio
    - name: Install platformIO libraries
      run: pio lib install
    - name: Run PlatformIO
      run: platformio run
      
